### ISSUE TITLE
Numpy version issue

### ISSUE THREAD

**Issue by catrionamurray** [zkbt/exoplanet-atlas#25]
I get this error with a new conda environment, Python 3.9 and installing exoplanet-atlas (it seems to be a result of numpy v '1.26.0'). Forcing install of numpy v1.23.1 solves this issue.

[exoplanetarchivedownloader] Attempting to freshly download data from 
                             https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+*+from+ps&format=csv
[exoplanetarchivedownloader] Download successful! Saved file to /Users/catrionamurray/Library/CloudStorage/OneDrive-UCB-O365/PycharmProjects/chromatic_fitting/notebooks/TOI3884/exoatlas-downloads/data/nea-ps.txt
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
File ~/anaconda3/envs/exoatlas/lib/python3.9/site-packages/exoatlas/populations/Population.py:1447, in PredefinedPopulation.__init__(self, label, remake, skip_update, **plotkw)
   1446     assert remake == False
-> 1447     standard = self.load_standard(skip_update=skip_update)
   1448 except (IOError, FileNotFoundError, AssertionError):
   1449     # or create a new standardized table and save it

File ~/anaconda3/envs/exoatlas/lib/python3.9/site-packages/exoatlas/populations/Population.py:1541, in PredefinedPopulation.load_standard(self, skip_update)
   1540     old = check_if_needs_updating(self.standard_path, self.expiration)
-> 1541     assert old == False
   1543 # keywords for reading a standardized table

AssertionError: 

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[2], line 2
      1 # create a dictionary of populations
----> 2 exo = TransitingExoplanets()
      3 solar = SolarSystem()
      4 pops = {'solar':solar,
      5         'exo':exo}

File ~/anaconda3/envs/exoatlas/lib/python3.9/site-packages/exoatlas/populations/TransitingExoplanets.py:10, in TransitingExoplanets.__init__(self, **kw)
      9 def __init__(self, **kw):
---> 10     Exoplanets.__init__(self, **kw)
     12     # set the label
     13     self.label = "Transiting Exoplanets"

File ~/anaconda3/envs/exoatlas/lib/python3.9/site-packages/exoatlas/populations/Exoplanets.py:36, in Exoplanets.__init__(self, label, remake, **plotkw)
     12 """
     13 Initialize a population of all known exoplanets
     14 using the NASA Exoplanet Archive `ps` table.
   (...)
     33     default plotting styles, like alpha` or `zorder`
     34 """
     35 # set up the population
---> 36 PredefinedPopulation.__init__(self, label=label, remake=remake, **plotkw)

File ~/anaconda3/envs/exoatlas/lib/python3.9/site-packages/exoatlas/populations/Population.py:1450, in PredefinedPopulation.__init__(self, label, remake, skip_update, **plotkw)
   1447     standard = self.load_standard(skip_update=skip_update)
   1448 except (IOError, FileNotFoundError, AssertionError):
   1449     # or create a new standardized table and save it
-> 1450     standard = self.ingest_table(remake=remake)
   1452 # initialize with a standard table
   1453 Population.__init__(self, standard=standard, label=label, **plotkw)

File ~/anaconda3/envs/exoatlas/lib/python3.9/site-packages/exoatlas/populations/Population.py:1473, in PredefinedPopulation.ingest_table(self, **kwargs)
   1470 raw = self.load_raw()
   1472 # trim elements from raw table as necessary
-> 1473 trimmed = self.trim_raw(raw)
   1475 try:
   1476     # create a standardized table from the array
   1477     standard = self.create_standard(trimmed)

File ~/anaconda3/envs/exoatlas/lib/python3.9/site-packages/exoatlas/populations/Exoplanets.py:93, in Exoplanets.trim_raw(self, raw)
     77 """
     78 Trim the raw table down to ones with reasonable values.
     79 
   (...)
     88     A raw, trimmed, unstandardized table.
     89 """
     91 masks = {}
---> 93 ok = np.ones(len(raw)).astype(np.bool)
     94 for k in masks:
     95     ok *= masks[k]

File ~/anaconda3/envs/exoatlas/lib/python3.9/site-packages/numpy/__init__.py:324, in __getattr__(attr)
    319     warnings.warn(
    320         f"In the future `np.{attr}` will be defined as the "
    321         "corresponding NumPy scalar.", FutureWarning, stacklevel=2)
    323 if attr in __former_attrs__:
--> 324     raise AttributeError(__former_attrs__[attr])
    326 if attr == 'testing':
    327     import numpy.testing as testing

AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by zkbt** [comment]
I *believe* this was resolved sometime by replacing the `np.bool` with simple `bool`. I won't quite close this yet until I update the dependencies and check that it works in a clean environment, but hopefully the latest `develop` version should be safe to use?

**Comment by zkbt** [comment]
This appears to be resolved somewhere in or before version 0.3.3 (for example, in #35 ).
